# 使用 Node 的官方镜像（建议选择稳定的版本，如 node:16-alpine）
image: node:16-alpine

stages:
  - build
  - deploy

# 缓存 node_modules，加速下次构建
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# 构建阶段：安装依赖、构建项目、导出静态文件
build:
  stage: build
  script:
    - echo "安装依赖…"
    - npm ci
    - echo "构建 Next.js 应用…"
    - npm run build
    - echo "导出静态文件…"
    - npm run export
  artifacts:
    paths:
      - out            # Next.js 默认将静态导出内容放在 out 目录
    expire_in: 1 hour  # 构建产物保留时间，根据需要调整
  only:
    - main           # 或者你使用 master 分支

# 部署阶段：GitLab Pages 部署要求最终的文件放在 public 目录下
pages:
  stage: deploy
  script:
    - echo "部署到 GitLab Pages…"
    - mv out public   # GitLab Pages 默认读取 public 目录内容
  artifacts:
    paths:
      - public
  only:
    - main